package parser;
public class sym {
    public static final int EOF = 0;
    public static final int INT = 1;
    public static final int ID = 2;
    public static final int IF = 3;
    public static final int RETURN = 4;
    public static final int NUM = 5;
    public static final int PLUS = 6;
    public static final int LESS_THAN_EQUALS = 7;
    public static final int EQUALS_EQUALS = 8;
    public static final int NOT_EQUALS = 9;
    public static final int GREATER_THAN = 10;
    public static final int GREATER_THAN_EQUALS = 11;
    public static final int LPAREN = 12;
    public static final int RPAREN = 13;
    public static final int LBRACKET = 14;
    public static final int RBRACKET = 15;
    public static final int LBRACE = 16;
    public static final int RBRACE = 17;
    public static final int COMMA = 18;
    public static final int MINUS = 19;
    public static final int MULTIPLY = 20;
    public static final int DIVIDE = 21;
    public static final int INTLIT = 22;
    public static final int STRINGLIT = 23;
    public static final int FLOATLIT = 24;
    public static final int ELSE = 25;
    public static final int TRUE = 26;
    public static final int FALSE = 27;
    public static final int FLOAT = 28;
    public static final int WHILE = 29;
    public static final int PUBLIC = 30;
    public static final int BOOLEAN = 31;
    public static final int PRIVATE = 32;
    public static final int PROTECTED = 33;
    public static final int VOID = 34;
    public static final int FOR = 35;
    public static final int LESS_THAN = 36;
    public static final int EQUALS = 37;
    public static final int IDENTIFIER = 38;
    public static final int SEMICOLON = 39;

}
