
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MULTIPLY = 4;
  public static final int ELSE = 20;
  public static final int SEMICOLON = 17;
  public static final int PLUS = 2;
  public static final int INT = 23;
  public static final int RBRACE = 16;
  public static final int RPAREN = 14;
  public static final int WHILE = 21;
  public static final int GREATER_THAN = 11;
  public static final int IDENTIFIER = 31;
  public static final int RETURN = 26;
  public static final int FLOATLIT = 33;
  public static final int TRUE = 27;
  public static final int IF = 19;
  public static final int LPAREN = 13;
  public static final int LBRACE = 15;
  public static final int PUBLIC = 29;
  public static final int GREATER_THAN_EQUALS = 12;
  public static final int BOOLEAN = 25;
  public static final int INTLIT = 32;
  public static final int EQUALS = 6;
  public static final int COMMA = 18;
  public static final int FLOAT = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int LESS_THAN = 9;
  public static final int STRINGLIT = 34;
  public static final int FALSE = 28;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int NOT_EQUALS = 8;
  public static final int LESS_THAN_EQUALS = 10;
  public static final int EQUALS_EQUALS = 7;
  public static final int FOR = 22;
  public static final int VOID = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "EQUALS",
  "EQUALS_EQUALS",
  "NOT_EQUALS",
  "LESS_THAN",
  "LESS_THAN_EQUALS",
  "GREATER_THAN",
  "GREATER_THAN_EQUALS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "COMMA",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "RETURN",
  "TRUE",
  "FALSE",
  "PUBLIC",
  "VOID",
  "IDENTIFIER",
  "INTLIT",
  "FLOATLIT",
  "STRINGLIT"
  };
}

